### ISSUE TITLE
Mod isn't working in v142

### ISSUE THREAD

**Issue by MaxEichinger43** [guiYMOUR/mindustry-Extra-Utilities-mod#28]
I downloaded the mod mainly because of the turret "prism", but it doesn't work! I can't even import it (see attached file)

![import-error](https://user-images.githubusercontent.com/126464027/224564616-014ddcb3-3297-4544-8ed4-2f441ef5c11f.png)

**Comment by guiYMOUR** [comment]
okay, but please let me investigate two more issues
Firstly, is it because your device is an iPhone or iPad?
If this is the reason, then it is because these two devices do not support running mod containing Java or JavaScript
Secondly, is your download the EUxxx.jar file under Release?
if not, please go to https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod/releases and download this file
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/77377005/230292005-a645f6f0-894f-4fe9-b6c8-f378beb38ad5.png">
